config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  post '/print', to: 'pages#print', as: :print
  mount CitizenBudgetModel::Engine => '/admin'
end

app/models/report.rb
# @see https://github.com/prawnpdf/prawn/blob/master/lib/prawn/view.rb
class Report
  include Prawn::View

  include CitizenBudgetModel::AdminHelper

  # Generates a report of the impacts of changes to variables.
  #
  # @param [CitizenBudgetModel::Simulator] simulator a simulator
  # @param [Hash{Symbol,String=>Float,String}] variables variables
  def initialize(simulator, variables)
    @simulator = simulator
    @variables = {}

    variables.each do |key,value|
      @variables[key] = Float(value)
    end
  end

  # Sets the document's margins to one inch.
  def document
    @document ||= Prawn::Document.new(margin: 72)
  end

  # Generates the report.
  #
  # @see http://prawnpdf.org/manual.pdf
  # @see http://prawnpdf.org/prawn-table-manual.pdf
  def generate
    # Calculate the maximum bar value.
    maximum = 0
    @simulator.sections.each do |section|
      section.questions.each do |question|
        max = [question.solve(question.minimum).abs, question.solve(question.maximum).abs].max
        if max > maximum
          maximum = max
        end
      end
    end

    bar_cell_width = 36.0
    default_options = {
      width: margin_box.width, # 468pt, 6.5in
      column_widths: [180, 72, 72, 72, 36, 36],
      cell_style: {
        borders: [], # eliminates black border
        padding: [4, 0, 4, 0],
      },
    }

    font_size 10
    image Rails.root.join('app', 'assets', 'images', 'header.jpg'), width: margin_box.width
    move_down 20
    text _('All revenue impacts in millions'), align: :center, color: '#999999'

    @simulator.sections.each do |section|
      # Header row
      data = [[
        UnicodeUtils.nfc(section.title), # merge diacritics and letters
        _('Default'),
        _('Your choice'),
        _('Impact'),
        '',
        '',
      ]]

      # Data rows
      borders = [] # baselines for bars
      section.questions.each_with_index do |question,index|
        value = @variables.fetch(question.machine_name)
        solution = question.solve(value)

        bars = ['', '']
        if solution.zero?
          solution = solution.abs
        else
          bar_width = (solution.abs / maximum * bar_cell_width).ceil

          if solution < 0
            filename = 'negative.png'
            position = bar_cell_width - bar_width
            border = :right
            column = 0
          else
            filename = 'positive.png'
            position = 0
            border = :left
            column = 1
          end

          bars[column] = {
            image: Rails.root.join('app', 'assets', 'images', filename),
            image_width: bar_width,
            image_height: 10,
            position: position,
            padding: [4, 0, 4, 0],
          }

          borders << [column + 4, index + 1, border]
        end

        row = [
          UnicodeUtils.nfc(question.name), # merge diacritics and letters
          value_formatter(question).call(question.default_value),
          value_formatter(question).call(value),
          currency_formatter(precision: 0).call(solution / 1_000_000.0),
          bars[0],
          bars[1],
        ]

        data << row
      end

      # If we set header: true, it's impossible to know which row will break
      # across the page when drawing the bars.
      table(data, default_options) do
        row(0).font_style = :bold
        columns(1..-1).align = :center

        # Setting borders in the cell (above) doesn't seem to work.
        borders.each do |column,row,border|
          columns(column).rows(row).borders = [border]
        end
      end
      move_down 20
    end

    data = [[
      _('Total revenue impacts'),
      '',
      '',
      currency_formatter(precision: 2, significant: true).call(@simulator.solve(@variables) / 1_000_000.0),
      '',
      '',
    ]]

    stroke_horizontal_rule
    move_down 20
    table(data, default_options) do
      row(0).font_style = :bold
      columns(1..-1).align = :center
    end
  end

private

  def number_to_currency(*args)
    ActionController::Base.helpers.number_to_currency(*args)
  end

  def number_to_percentage(*args)
    ActionController::Base.helpers.number_to_percentage(*args)
  end

  def number_with_precision(*args)
    ActionController::Base.helpers.number_with_precision(*args)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  # If the query string sets the locale, updates the session's locale. Sets the
  # current locale to the session's locale. If the session's locale is not set,
  # it sets the current locale to the default locale and renders a splash page.
  def set_locale
    if params[:locale].present? && I18n.available_locales.include?(params[:locale].to_sym)
      session[:locale] = params[:locale]
    end

    I18n.locale = session[:locale] || I18n.default_locale

    unless session[:locale]
      render 'pages/switcher'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_simulator

  def index
  end

  def print
    report = Report.new(@simulator, params[:variables])
    report.generate
    send_data report.render, disposition: 'inline', filename: 'Ready_Reckoner_Report.pdf', type: 'application/pdf'
  end

private

  def set_simulator
    @simulator = CitizenBudgetModel::Simulator.where(active: true).includes([:translations, {sections: [:translations, {questions: :translations}]}]).first!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include CitizenBudgetModel::AdminHelper

  # Returns whether all questions in the section use the same step.
  #
  # @param [CitizenBudgetModel::Section] section a section
  # @return [Boolean] whether all questions in the section use the same step
  def same_step?(section)
    expected = section.questions.first.step
    section.questions.drop(1).all? do |question|
      question.step == expected
    end
  end

  # Formats a record's attribute's value.
  #
  # @param record a record
  # @param [Symbol] attribute an attribute of the record
  # @param [Hash] options formatting options
  # @return [String] a formatted attribute value
  def format(record, attribute, options = {})
    value_formatter(record, options).call(record.send(attribute))
  end

  # @param [CitizenBudgetModel::Question] question a question
  # @return [ActiveSupport::SafeBuffer] an "input" tag of type "range" with a
  #   "datalist" tag describing its options
  # @see http://afarkas.github.io/webshim/demos/demos/cfgs/input-range.html
  def range(question)
    id = "#{question.id}-#{question.name.parameterize}"
    minimum = integer(question.minimum)
    maximum = integer(question.maximum)
    step = integer(question.step)
    default_value = integer(question.default_value)

    values_with_labels = [minimum, maximum]
    unless request.headers['X_MOBILE_DEVICE']
      values_with_labels.insert(1, default_value)
    end

    options = ActiveSupport::SafeBuffer.new
    (minimum..maximum).step(step) do |value| # range needs min and max to respect step
      # Only display labels for default, minimum and maximum, to avoid crowding.
      attributes = {value: value}
      if values_with_labels.include?(value)
        attributes[:label] = value_formatter(question).call(value)
      end
      options << content_tag('option', nil, attributes)
    end

    tag(:input, {
      id: question.machine_name,
      name: "variables[#{question.machine_name}]",
      type: 'range',
      min: minimum,
      max: maximum,
      step: step,
      value: default_value,
      list: id,
    }) +
    content_tag('datalist', content_tag('select', options), id: id)
  end

private

  def integer(number)
    integer = Integer(number)
    if integer == number
      integer
    else
      number
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="<%= I18n.locale %>">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title><%= _('Ready Reckoner') %></title>
<meta name="description" content="<%= _('Provides a starting point for parliamentarians and the general public to broadly estimate the revenue impacts of changes to the federal tax system.') %>">
<meta name="viewport" content="width=device-width, initial-scale=1">
<% I18n.available_locales.each do |locale| %>
  <% unless I18n.locale == locale %>
<link rel="alternate" hreflang="<%= locale.downcase %>" href="<%= root_url %>?locale=<%= locale %>" />
  <% end %>
<% end %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= csrf_meta_tags %>
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
<%# We can't use Zepto, as it doesn't support Internet Explorer 9 and lower. %>
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="/assets/polyfiller.js"></script>
<%= javascript_include_tag 'webshim' %>
</head>
<body>

<div id="banner">
  <%= image_tag 'header.jpg', size: '768x113', alt: _('Parliamentary Budget Officer'), class: 'img-responsive center-block' %>
</div>

<%= yield %>

<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-21866813-15', 'auto');
ga('send', 'pageview');
</script>

</body>
</html>

app/views/pages/_popover.html.erb
<% if record.popover.present? %>
  <a href="#" data-toggle="popover" data-content="<%= record.popover %>" data-trigger="focus">
    <span class="glyphicon glyphicon-info-sign"></span>
  </a>
<% end %>

app/views/pages/index.html.erb
<div id="locale">
  <% I18n.available_locales.each do |locale| %>
    <% unless I18n.locale == locale %>
      <%= link_to _(locale), root_path(locale: locale) %>
    <% end %>
  <% end %>
</div>

<div class="container-fluid">
  <%= form_tag print_path, method: 'post' do %>

  <header>
    <h1><%= _('Ready Reckoner') %></h1>

    <%= simple_format(_("The Parliamentary Budget Officer has prepared this tool to allow parliamentarians and the general public to broadly estimate the revenue impacts of changes to the federal tax system."), class: 'lead center') %>
  </header>

  <div class="row" id="simulator">
    <div class="col-sm-9" role="main">
      <% @simulator.sections.each_with_index do |section,index| %>
        <table class="table">
          <% if index.zero? %>
            <caption class="text-muted">
              <%= _('All revenue impacts in millions') %>
            </caption>
          <% end %>
          <thead>
            <tr id="<%= section.title.parameterize %>">
              <th class="section">
                <%= section.title %>
                <%= render partial: 'popover', locals: {record: section} %>
              </th>
              <th class="text-center impact-column">
                <% if same_step?(section) %>
                  <span class="hidden-xs hidden-sm">
                    <%= _('Impact per %{step} change') % {step: format(section.questions[0], :step)} %>
                  </span>
                  <span class="hidden-md hidden-lg">
                    <%= _('per %{step} change') % {step: format(section.questions[0], :step)} %>
                  </span>
                <% end %>
              </th>
              <th class="text-center widget-column">
                <%= _('Your choice') %>
              </th>
            </tr>
          </thead>
          <tbody>
            <% section.questions.each do |question| %>
              <tr>
                <td class="question">
                  <%= question.name %>
                  <%= render partial: 'popover', locals: {record: question} %>
                </td>
                <td class="text-center impact-column">
                  <%= number_to_currency((question.unit_value_down.abs + question.unit_value_up.abs) / 2 * question.step / 1_000_000.0, strip_insignificant_zeros: true, precision: 0) %>
                </td>
                <td class="widget widget-column">
                  <%= range(question) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
    <div class="col-sm-3">
      <div class="hidden-print hidden-xs" role="complementary" id="sidebar">
        <ul class="nav">
          <% @simulator.sections.each do |section| %>
            <li>
              <a href="#<%= section.title.parameterize %>"><%= section.title %></a>
            </li>
          <% end %>
        </ul>

        <div id="impacts-sidebar"></div>
      </div>
    </div>
  </div>

  <div class="row" id="submit">
    <div id="impacts-summary"></div>

    <%= button_tag _('Print a PDF report of your changes'), class: 'btn btn-primary btn-lg' %>
  </div>

  <footer>
    <p class="lead center"><%= _('This analysis is based on <a href="http://www.statcan.gc.ca/microsimulation/spsdm-bdmsps/spsdm-bdmsps-eng.htm">SPSD/M</a>. The assumptions and calculations underlying the simulation results were prepared by the PBO and the responsibility for the use and interpretation of these data is entirely that of the authors. The user interface was developed by <a href="http://www.opennorth.ca/">Open North</a>.').html_safe %></p>
  </footer>

  <% end %>
</div>

<script>
var total_revenue = <%= @simulator.total_revenue %>;
</script>
<%= render partial: 'citizen_budget_model/simulators/equation', locals: {equation: @simulator.working_equation} %>
<%= javascript_include_tag 'application' %>

app/views/pages/switcher.html.erb
<div class="container-fluid" id="locales">
  <div class="row">
    <% I18n.available_locales.each_with_index do |locale,index| %>
      <div class="col-sm-6<% if index.even? %> text-right<% end %>">
        <h1><%= _('Ready Reckoner', locale: locale) %></h1>

        <%= link_to _('Enter', locale: locale), root_path(locale: locale), class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>
  </div>
</div>